#!/bin/bash

filename="Screenshot_"`date +"%Y-%m-%d_%H:%M:%S"`".png"

case "$1" in
-s)
notify-send 'print screen: select !'&& scrot -s $filename -e 'mv $f ~/temp/'&& notify-send "screen shot! $filename"
;;

-d)
pic="`date|md5sum|head -c 6`.png"
notify-send 'select an area and upload to Dropbox !'
scrot -s $pic -e 'mv $f ~/Dropbox/Public/screenshots/ && echo https://dl.dropbox.com/u/84471951/screenshots/$n | xsel -b -i -l /dev/null '&& notify-send "url copyed $pic" 
;;

*)
scrot $filename -e 'mv $f ~/temp/'  && notify-send "screen shot! $filename"
;;
esac
